"""Research helpers for exploratory analysis and offline dataset generation."""

from src.research.event_dataset import (
    DEFAULT_EVENT_DATASET_OUTPUT_DIR,
    DatasetIntegrityError,
    EventDatasetBuild,
    EventDatasetBuildConfig,
    EventDatasetBuildResult,
    EventLabelConfig,
    TradeCostAssumptions,
    materialize_event_dataset,
)
from src.research.wallet_exploration import (
    DEFAULT_WALLET_TABLES,
    SUPPORTED_COHORT_METRICS,
    WalletActivityTrade,
    WalletClosedPositionPoint,
    WalletCohortProfile,
    WalletOpenPositionSnapshot,
    WalletRawCaptureInfo,
    WalletSeedMetadata,
    get_table_counts,
    latest_raw_capture_path,
    list_latest_wallet_dataset_captures,
    list_wallet_activity_trades,
    list_wallet_closed_position_points,
    list_wallet_cohort_profiles,
    list_wallet_open_positions,
    list_wallet_seed_metadata,
    load_json_capture,
    load_jsonl_capture,
    market_label,
    wallet_display_name,
)

__all__ = [
    "DEFAULT_EVENT_DATASET_OUTPUT_DIR",
    "DEFAULT_WALLET_TABLES",
    "DatasetIntegrityError",
    "EventDatasetBuild",
    "EventDatasetBuildConfig",
    "EventDatasetBuildResult",
    "EventLabelConfig",
    "SUPPORTED_COHORT_METRICS",
    "TradeCostAssumptions",
    "WalletActivityTrade",
    "WalletClosedPositionPoint",
    "WalletCohortProfile",
    "WalletOpenPositionSnapshot",
    "WalletRawCaptureInfo",
    "WalletSeedMetadata",
    "get_table_counts",
    "latest_raw_capture_path",
    "list_latest_wallet_dataset_captures",
    "list_wallet_activity_trades",
    "list_wallet_closed_position_points",
    "list_wallet_cohort_profiles",
    "list_wallet_open_positions",
    "list_wallet_seed_metadata",
    "load_json_capture",
    "load_jsonl_capture",
    "market_label",
    "materialize_event_dataset",
    "wallet_display_name",
]
